### ISSUE TITLE
Striped background Image clashing with text

### ISSUE THREAD

**Issue by javik223** [javik223/GBC#3]
On mobile, the striped background image is clashing with the text. I think you should push the stripped background to the right. Also you might want to reduce the background size on mobile as well.

<img width="268" alt="Screenshot 2020-10-15 at 09 50 57" src="https://user-images.githubusercontent.com/2006299/96100553-683ede80-0ecc-11eb-8ad5-dd05d1bcca6c.png">

The same applies on desktop. Below is the current view on Desktop and the actual view in the design

[Current View]
<img width="630" alt="Screenshot 2020-10-15 at 09 50 35" src="https://user-images.githubusercontent.com/2006299/96100676-8a386100-0ecc-11eb-966b-5fbf7e4b6bc0.png">

[Actual View]
<img width="268" alt="Screenshot 2020-10-15 at 09 50 57" src="https://user-images.githubusercontent.com/2006299/96100688-8f95ab80-0ecc-11eb-9502-bbeffaf0643e.png">

**Comment by samakintunde37** [comment]
@javik223  The actual asset has whitespace in the PNG, causing this. I'll fix this soon.
